export const ERROR_CODES = [
  'VALIDATION_ERROR',
  'UNAUTHORIZED',
  'FORBIDDEN',
  'RESOURCE_NOT_FOUND',
  'INTERNAL_ERROR',

  'INVALID_OAUTH_CODE',
  'OAUTH_PROVIDER_ERROR',
  'INVALID_REFRESH_TOKEN',

  'ALREADY_DRAWN_TODAY',
  'REVIEW_CLOSED',
  'REVIEW_ALREADY_EXISTS',
  'REVIEW_EMPTY_INPUT',
  'REVIEW_TOO_MANY_TAGS',
] as const;

export type ErrorCode = (typeof ERROR_CODES)[number];
