import {
  MS_PER_DAY,
  MS_PER_MINUTE,
  MS_PER_SECOND,
  REFRESH_TOKEN_TTL_DAYS,
} from '@saeteum/shared';
import {
  ACCESS_TOKEN_TTL_MINUTES,
  CODE_TTL_SECONDS,
  STATE_TTL_MINUTES,
} from './auth.constant';

export const AUTH_EXPIRATION = {
  ACCESS_TOKEN_EXPIRES_IN: `${ACCESS_TOKEN_TTL_MINUTES}m`,
  REFRESH_TOKEN_TTL_MS: REFRESH_TOKEN_TTL_DAYS * MS_PER_DAY,
  STATE_TTL_MS: STATE_TTL_MINUTES * MS_PER_MINUTE,
  CODE_TTL_MS: CODE_TTL_SECONDS * MS_PER_SECOND,
} as const;
