import 'dotenv/config';
import { db } from './index';
import { missions, missionCategoryEnum } from './schema';

type MissionCategory = (typeof missionCategoryEnum.enumValues)[number];

const MISSIONS: { category: MissionCategory; content: string }[] = [
  // 자연
  { category: 'nature', content: '하늘 사진 찍기' },
  { category: 'nature', content: '구름 모양 관찰하기' },
  { category: 'nature', content: '나무 한 그루 자세히 살펴보기' },
  { category: 'nature', content: '바람 소리에 귀 기울이기' },
  { category: 'nature', content: '근처 화단이나 풀밭 걸어보기' },
  { category: 'nature', content: '주변에서 눈에 띄는 식물 하나 관찰해보기' },
  { category: 'nature', content: '창문 열고 바깥 공기 마시기' },
  { category: 'nature', content: '낙엽이나 나뭇잎 하나 주워보기' },
  { category: 'nature', content: '새소리 들리는 곳 찾아보기' },
  { category: 'nature', content: '오늘 하늘색 세 번 확인하기' },
  { category: 'nature', content: '가까운 공원 벤치에 앉아있기' },
  { category: 'nature', content: '흙이나 나무 냄새 맡아보기' },
  { category: 'nature', content: '좋아하는 자연 소리 찾아 들어보기' },
  { category: 'nature', content: '식물 하나 돌봐주기' },
  { category: 'nature', content: '오늘 날씨를 한 단어로 표현해보기' },
  { category: 'nature', content: '근처에서 초록빛 식물 하나 찾아보기' },
  {
    category: 'nature',
    content: '자연물(돌, 나뭇가지, 잎 등) 하나 주워서 만져보기',
  },
  { category: 'nature', content: '하늘 대신 땅을 보면서 걸어보기' },
  { category: 'nature', content: '좋아하는 나무나 식물 사진 찍어두기' },
  { category: 'nature', content: '자연에서 볼 수 있는 색 세 가지 찾아보기' },

  // 탐험
  { category: 'exploration', content: '안 가본 골목 걸어보기' },
  { category: 'exploration', content: '평소와 다른 길로 귀가하기' },
  { category: 'exploration', content: '근처 낯선 카페 가보기' },
  { category: 'exploration', content: '처음 보는 간판 읽어보기' },
  { category: 'exploration', content: '동네 지도에서 안 가본 곳 표시하기' },
  {
    category: 'exploration',
    content: '엘리베이터 대신 계단으로 다른 층 구경하기',
  },
  { category: 'exploration', content: '버스나 지하철, 한 정거장 더 걸어보기' },
  { category: 'exploration', content: '처음 들어가보는 가게 구경하기' },
  { category: 'exploration', content: '동네 골목 끝까지 걸어가보기' },
  { category: 'exploration', content: '안 열어본 앱 하나 켜보기' },
  { category: 'exploration', content: '낯선 동네 이름 검색해보기' },
  { category: 'exploration', content: '자주 안 가는 층(옥상, 지하 등) 가보기' },
  { category: 'exploration', content: '평소 안 앉는 자리에 앉아보기' },
  { category: 'exploration', content: '새로운 산책 코스 만들어보기' },
  { category: 'exploration', content: '동네 지도 한 바퀴 훑어보기' },
  { category: 'exploration', content: '낯선 표지판 사진 찍기' },
  { category: 'exploration', content: '자판기 메뉴 구경하기' },
  { category: 'exploration', content: '처음 가는 편의점 들러보기' },
  { category: 'exploration', content: '다른 문으로 건물 들어가보기' },
  {
    category: 'exploration',
    content: '지도 앱으로 근처 안 가본 장소 찾아보기',
  },

  // 사람과의 연결
  { category: 'connection', content: '모르는 사람에게 인사하기' },
  { category: 'connection', content: '오랜만에 친구에게 안부 연락하기' },
  { category: 'connection', content: '가족에게 짧은 메시지 보내기' },
  { category: 'connection', content: '지나가는 사람에게 미소 짓기' },
  { category: 'connection', content: '동료나 친구에게 칭찬 한마디 하기' },
  { category: 'connection', content: '카페 직원에게 감사 인사 전하기' },
  { category: 'connection', content: 'SNS에서 응원 댓글 하나 남기기' },
  { category: 'connection', content: '옛 사진 한 장 골라 그 사람에게 보내기' },
  { category: 'connection', content: '"고맙다"는 말 오늘 한 번 해보기' },
  {
    category: 'connection',
    content: '엘리베이터에서 마주친 사람에게 인사하기',
  },
  { category: 'connection', content: '좋아하는 창작자에게 응원 메시지 남기기' },
  { category: 'connection', content: '가족과 짧은 통화하기' },
  { category: 'connection', content: '함께 일하는 사람에게 안부 물어보기' },
  { category: 'connection', content: '낯선 사람의 좋은 점 하나 발견해보기' },
  { category: 'connection', content: '이웃에게 가볍게 인사하기' },
  { category: 'connection', content: '오늘 만난 사람에게 진심으로 리액션하기' },
  { category: 'connection', content: '그리운 사람 이름 떠올려보기' },
  { category: 'connection', content: '친구에게 사진 한 장 보내기' },
  { category: 'connection', content: '도움을 준 사람에게 고맙다고 말하기' },
  { category: 'connection', content: '낯선 사람과 잠깐 스몰토크 해보기' },

  // 혼자만의 시간
  { category: 'solitude', content: '혼자 카페 가서 앉아있기' },
  { category: 'solitude', content: '5분간 눈 감고 명상하기' },
  { category: 'solitude', content: '아무것도 안 하고 가만히 있어보기' },
  { category: 'solitude', content: '좋아하는 음악 한 곡 온전히 듣기' },
  { category: 'solitude', content: '혼자 산책하며 생각 정리하기' },
  { category: 'solitude', content: '조용한 곳에서 차 한 잔 마시기' },
  { category: 'solitude', content: '스마트폰 없이 10분 보내기' },
  { category: 'solitude', content: '오늘 하루 감정 한 단어로 적어보기' },
  { category: 'solitude', content: '좋아하는 향 맡으며 잠깐 쉬기' },
  { category: 'solitude', content: '혼자 볼 영화나 드라마 정하고 보기' },
  { category: 'solitude', content: '심호흡 열 번 해보기' },
  { category: 'solitude', content: '침대에 누워 아무 생각 안 하기' },
  { category: 'solitude', content: '좋아하는 책 한 페이지 읽기' },
  { category: 'solitude', content: '혼자 산책로 끝까지 걸어보기' },
  { category: 'solitude', content: '나에게 하고 싶은 말 적어보기' },
  { category: 'solitude', content: '조용한 카페 구석 자리 찾아 앉기' },
  { category: 'solitude', content: '오늘 있었던 좋은 일 하나 떠올리기' },
  { category: 'solitude', content: '혼자 셀카 찍어보기' },
  { category: 'solitude', content: '좋아하는 향초나 디퓨저 켜보기' },
  { category: 'solitude', content: '나만의 루틴 하나 만들어보기' },

  // 몸 움직이기
  { category: 'movement', content: '10분 산책하기' },
  { category: 'movement', content: '계단으로 다니기' },
  { category: 'movement', content: '스트레칭 5분 하기' },
  { category: 'movement', content: '목과 어깨 풀어주기' },
  { category: 'movement', content: '제자리에서 점프 10번 하기' },
  { category: 'movement', content: '팔 벌려 크게 기지개 켜기' },
  { category: 'movement', content: '걷는 동안 자세 신경 써보기' },
  { category: 'movement', content: '앉았다 일어서기 10번 하기' },
  { category: 'movement', content: '까치발 20번 해보기' },
  { category: 'movement', content: '요가 동작 하나 따라 해보기' },
  { category: 'movement', content: '가벼운 춤 한 곡 춰보기' },
  { category: 'movement', content: '목 좌우로 돌리기 5번씩' },
  { category: 'movement', content: '평소보다 빠르게 걸어보기' },
  { category: 'movement', content: '손목·발목 돌리기' },
  { category: 'movement', content: '심박수 살짝 올리는 운동 3분 하기' },
  { category: 'movement', content: '벽 짚고 종아리 스트레칭하기' },
  { category: 'movement', content: '바른 자세로 5분 앉아있기' },
  { category: 'movement', content: '팔굽혀펴기나 스쿼트 5개 해보기' },
  { category: 'movement', content: '딴생각 없이 걷기에만 집중해보기' },
  { category: 'movement', content: '오늘 목표 걸음 수 정해서 걸어보기' },

  // 창작·기록
  { category: 'creation', content: '낙서 한 장 그려보기' },
  { category: 'creation', content: '오늘 하루 한 줄 일기 쓰기' },
  { category: 'creation', content: '사진 한 장 찍고 제목 붙여보기' },
  { category: 'creation', content: '좋아하는 문장 하나 필사하기' },
  { category: 'creation', content: '떠오르는 단어 다섯 개 적어보기' },
  { category: 'creation', content: '오늘의 기분을 색깔로 표현해보기' },
  { category: 'creation', content: '짧은 시 한 편 써보기' },
  { category: 'creation', content: '좋아하는 노래 가사 적어보기' },
  { category: 'creation', content: '오늘 먹은 음식 그려보기' },
  { category: 'creation', content: '손글씨로 짧은 메모 남기기' },
  { category: 'creation', content: '3분 타이머 놓고 즉흥 낙서하기' },
  { category: 'creation', content: '오늘의 장면을 글로 묘사해보기' },
  { category: 'creation', content: '나만의 캐릭터 하나 그려보기' },
  { category: 'creation', content: '감사한 일 세 가지 적어보기' },
  { category: 'creation', content: '오늘 본 것들 나열해보기' },
  { category: 'creation', content: '짧은 이야기 한 문단 써보기' },
  { category: 'creation', content: '좋아하는 색으로 낙서 채워보기' },
  { category: 'creation', content: '오늘의 소리를 글자로 표현해보기' },
  { category: 'creation', content: '미래의 나에게 편지 한 줄 쓰기' },
  { category: 'creation', content: '마음에 드는 사진 골라 이유 적어보기' },

  // 새로운 감각
  { category: 'sensation', content: '안 먹어본 음식 하나 먹어보기' },
  { category: 'sensation', content: '새로운 음악 장르 들어보기' },
  { category: 'sensation', content: '처음 맡아보는 향 찾아보기' },
  { category: 'sensation', content: '평소 안 마시던 음료 마셔보기' },
  { category: 'sensation', content: '눈 감고 소리에만 집중해보기' },
  { category: 'sensation', content: '새로운 팟캐스트 한 편 들어보기' },
  { category: 'sensation', content: '느낌이 다른 물건 만져보기' },
  { category: 'sensation', content: '매운맛이나 신맛 음식 시도해보기' },
  { category: 'sensation', content: '낯선 언어로 된 노래 들어보기' },
  { category: 'sensation', content: '평소 안 보던 장르의 영상 보기' },
  { category: 'sensation', content: '새로운 향수나 비누 냄새 맡아보기' },
  { category: 'sensation', content: '반대 손으로 평소 하던 일 해보기' },
  { category: 'sensation', content: '처음 들어보는 악기 소리 찾아 듣기' },
  { category: 'sensation', content: '평소와 다른 온도의 물로 씻어보기' },
  { category: 'sensation', content: '눈 감고 촉감으로 물건 맞혀보기' },
  { category: 'sensation', content: '새로운 브랜드 제품 하나 써보기' },
  { category: 'sensation', content: '낯선 나라 음식 사진 찾아보기' },
  { category: 'sensation', content: '낯선 소리 배경음으로 틀어놓기' },
  { category: 'sensation', content: '안 좋아하던 재료로 만든 요리 도전해보기' },
  { category: 'sensation', content: '처음 보는 색 조합 옷 입어보기' },

  // 정리·비움
  { category: 'declutter', content: '책상 위 정리하기' },
  { category: 'declutter', content: '스마트폰 사진첩 5장 정리하기' },
  { category: 'declutter', content: '안 쓰는 앱 하나 삭제하기' },
  { category: 'declutter', content: '가방 속 정리하기' },
  { category: 'declutter', content: '미루던 일 하나 처리하기' },
  { category: 'declutter', content: '30분 디지털 디톡스 해보기' },
  { category: 'declutter', content: '안 입는 옷 하나 골라두기' },
  { category: 'declutter', content: '이메일함 안 읽은 메일 정리하기' },
  { category: 'declutter', content: '서랍 하나 비우기' },
  { category: 'declutter', content: '오늘 할 일 목록 만들고 하나 지우기' },
  { category: 'declutter', content: '냉장고 유통기한 확인하기' },
  { category: 'declutter', content: '핸드폰 홈 화면 정리하기' },
  { category: 'declutter', content: '오래된 메모 정리하기' },
  { category: 'declutter', content: '안 쓰는 구독 서비스 점검하기' },
  { category: 'declutter', content: '신발장이나 현관 정리하기' },
  { category: 'declutter', content: '즐겨찾기 목록 정리하기' },
  { category: 'declutter', content: '안 쓰는 충전기·케이블 정리하기' },
  { category: 'declutter', content: '미룬 답장 하나 보내기' },
  { category: 'declutter', content: '화장대나 세면대 정리하기' },
  { category: 'declutter', content: '오늘 하루 계획 다시 점검해보기' },
];

async function seed() {
  await db.insert(missions).values(MISSIONS);
  console.log(`${MISSIONS.length}개 미션 등록 완료`);
  process.exit(0);
}

seed().catch((err) => {
  console.error(err);
  process.exit(1);
});
